In [1]:
import sys
from pathlib import Path
from dotenv import dotenv_values
import pandas as pd

# Load environment variables from the .env file
env_vars = dotenv_values()  # Load variables from the .env file

# Get the workspace path from the environment variables
WORKSPACE_PATH = Path(
    env_vars.get("WORKSPACE_PATH", "")
)  # Fetch WORKSPACE_PATH from .env

if not WORKSPACE_PATH:
    raise ValueError("WORKSPACE_PATH is not defined in the .env file or is empty.")

# Add the WORKSPACE_PATH folder to the Python path
sys.path.append(str(WORKSPACE_PATH))

# Import custom utility functions
from src.config.utils import (
    read_csv,
    split_string,
    left_join_excel_sheets,
    aggregate_vertical,
    write_excel,
)

DATA_DIR = Path(env_vars["DATA_DIR"])
RESULTS_DIR = Path(env_vars["RESULTS_DIR"])
MOMENT_OF_SUICIDE_FEATURES = split_string(env_vars["MOMENT_OF_SUICIDE_FEATURES"])
SOCIO_DEMOGRAPHIC_FEATURES = split_string(env_vars["SOCIO_DEMOGRAPHIC_FEATURES"])

In [2]:
# Read CSV File
csv_file_path = DATA_DIR / "processed" / "encoded_data.csv"
df_encoded = read_csv(csv_file_path)

c:\Users\huber\OneDrive\Dokumenty\GitHub\ippan_suicide_study\src\config\utils.py:139: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  return pd.read_csv(file_path, **kwargs)

In [3]:
excel_file_path = DATA_DIR / "processed" / "lca_group_results.xlsx"
df_lca_classes = left_join_excel_sheets(excel_file_path, base_df=None, on="ID")

In [4]:
FEATURES = list(set(SOCIO_DEMOGRAPHIC_FEATURES + MOMENT_OF_SUICIDE_FEATURES))
columns_to_aggregate = [
    column
    for column in df_encoded.columns
    if any(column.startswith(feature) for feature in FEATURES)
]
class_columns = [
    column for column in df_lca_classes.columns if column.endswith("_class")
]

In [5]:
df = df_encoded.merge(df_lca_classes[["ID"] + class_columns], on="ID", how="left")

In [6]:
df = df[class_columns + columns_to_aggregate]

In [7]:
# Apply the function
count_result = aggregate_vertical(
    df,
    index_columns=class_columns,
    header="Count",
    agg_func="count",
)
count_result

                         Count
Column
LCA_Group_AF_class  1.0  40104
                    2.0  25982
                    3.0  24075
                    4.0  19140
                    5.0   9541
LCA_Group_AG_class  1.0  37810
                    2.0  26287
                    3.0  22027
                    4.0  20265
                    5.0  12453
LCA_Group_AGF_class 1.0  38447
                    2.0  31378
                    3.0  22875
                    4.0  16563
                    5.0   9579

In [11]:
write_excel(
    file_path=RESULTS_DIR / "lca_class_exploration.xlsx",
    data=count_result,
    sheet_name="count_result",
    mode="w",
    index=True,
)

In [12]:
# Apply the function
feature_result = aggregate_vertical(
    df,
    index_columns=class_columns,
    target_columns=columns_to_aggregate,
    header="",
    agg_func="sum",
)
feature_result

                         Gender  Marital_Cohabitant  Marital_Cohabiting  \
Column
LCA_Group_AF_class  1.0   28937                1484                  88
                    2.0   18785                1596                 100
                    3.0   18110                1226                  83
                    4.0   14160                1449                 114
                    5.0    7593                 195                  23
LCA_Group_AG_class  1.0   27601                2189                 142
                    2.0   19386                 620                  22
                    3.0   15828                1516                 132
                    4.0   15128                1023                  83
                    5.0    9642                 602                  29
LCA_Group_AGF_class 1.0   28673                1918                 124
                    2.0   23320                1477                  91
                    3.0   16706                1131                  79
                    4.0   11578                1172                  90
                    5.0    7308                 252                  24

                         Marital_Divorced  Marital_Married  Marital_Separated  \
Column
LCA_Group_AF_class  1.0              3188            11642                166
                    2.0              1261            16099                 86
                    3.0              2090             9224                136
                    4.0              2387             4733                155
                    5.0               561             2196                 26
LCA_Group_AG_class  1.0              4209             9738                224
                    2.0               749            13757                 43
                    3.0              2367             6284                159
                    4.0              1774             7126                115
                    5.0               388             6989                 28
LCA_Group_AGF_class 1.0              2507            15689                169
                    2.0              2661            10196                138
                    3.0              1914             6847                 95
                    4.0              1671             6300                115
                    5.0               734             4862                 52

                         Marital_Single  Marital_Widowed  Education_Higher  \
Column
LCA_Group_AF_class  1.0           19836             3700              3334
                    2.0            6557              283              2766
                    3.0           10280             1036              1905
                    4.0            9204             1098              2131
                    5.0            6305              235               715
LCA_Group_AG_class  1.0           18127             3181              3541
                    2.0           10019             1077              2447
                    3.0           10621              948              2622
                    4.0            9428              716              1414
                    5.0            3987              430               827
LCA_Group_AGF_class 1.0           16860             1180              3490
                    2.0           15164             1651              2597
                    3.0           10440             2369              2172
                    4.0            6385              830              1512
                    5.0            3333              322              1080

                         Education_LowerSecondary  ...  Context_Other  \
Column                                             ...
LCA_Group_AF_class  1.0                       148  ...           6214
                    2.0                       104  ...           3822
                    3.0                       162  ...           4562
                    4.0                        92  ...           2672
                    5.0                        55  ...           1278
LCA_Group_AG_class  1.0                       127  ...           5520
                    2.0                       111  ...           3958
                    3.0                       182  ...           3338
                    4.0                        87  ...           3463
                    5.0                        54  ...           2269
LCA_Group_AGF_class 1.0                       175  ...           5780
                    2.0                       143  ...           5001
                    3.0                       101  ...           3460
                    4.0                       100  ...           3106
                    5.0                        42  ...           1201

                         Context_FamilyConflict  Context_SchoolWork  \
Column
LCA_Group_AF_class  1.0                    5371                 872
                    2.0                    5133                 683
                    3.0                    4424                 665
                    4.0                    2603                 375
                    5.0                    1143                 284
LCA_Group_AG_class  1.0                    5375                 808
                    2.0                    4289                 642
                    3.0                    3677                 590
                    4.0                    3106                 543
                    5.0                    2227                 296
LCA_Group_AGF_class 1.0                    6132                 900
                    2.0                    4547                 660
                    3.0                    3291                 564
                    4.0                    2985                 556
                    5.0                    1719                 199

                         Context_MentalHealth  Context_HealthLoss  \
Column
LCA_Group_AF_class  1.0                 15070                3402
                    2.0                  9285                1926
                    3.0                  6912                1580
                    4.0                  8251                1436
                    5.0                  3847                 534
LCA_Group_AG_class  1.0                 14511                3339
                    2.0                  9592                2150
                    3.0                  8022                1148
                    4.0                  7154                1343
                    5.0                  4086                 898
LCA_Group_AGF_class 1.0                 13978                2652
                    2.0                 11358                2516
                    3.0                  8359                1889
                    4.0                  5451                1121
                    5.0                  4219                 700

                         Context_HeartBreak  Context_CloseDeath  \
Column
LCA_Group_AF_class  1.0                5269                1121
                    2.0                2934                 537
                    3.0                3426                 670
                    4.0                2271                 566
                    5.0                1785                 195
LCA_Group_AG_class  1.0                4718                1132
                    2.0                3237                 602
                    3.0                3467                 561
                    4.0                2769                 502
                    5.0                1494                 292
LCA_Group_AGF_class 1.0                5759                 886
                    2.0                4177                 873
                    3.0                3132                 723
                    4.0                1811                 416
                    5.0                 806                 191

                         Context_Finances  Context_Crime  Context_Disability
Column
LCA_Group_AF_class  1.0              2630            281                 218
                    2.0              1574            186                 109
                    3.0              1766            200                 145
                    4.0               973             95                 114
                    5.0               439             63                  50
LCA_Group_AG_class  1.0              2260            244                 257
                    2.0              1634            217                 146
                    3.0              1219            158                  81
                    4.0              1387            137                  99
                    5.0               882             69                  53
LCA_Group_AGF_class 1.0              2194            320                 157
                    2.0              2111            202                 215
                    3.0              1453            134                 131
                    4.0              1124            123                  64
                    5.0               500             46                  69

[15 rows x 64 columns]

In [13]:
write_excel(
    file_path=RESULTS_DIR / "lca_class_exploration.xlsx",
    data=feature_result,
    sheet_name="feature_result",
    mode="a",
    index=True,
)